### ISSUE TITLE
issues with schedules that run more frequently than once per hour 

### ISSUE THREAD

**Issue by talbright** [krux/starport#43]
```scala
override lazy val schedule = Schedule.cron.startTodayAt(19, 15, 0).every(Minute(30))
```

![Screen Shot 2019-09-03 at 5 34 00 PM](https://user-images.githubusercontent.com/212177/64210401-26420d00-ce71-11e9-917c-fccdcae1fb70.png)

![Screen Shot 2019-09-03 at 5 33 51 PM](https://user-images.githubusercontent.com/212177/64210410-29d59400-ce71-11e9-90be-2af9f6449d98.png)

**Comment by realstraw** [comment]
Cannot really reproduce this anymore but added unit test. Going to close this and we can reopen or add more detail if this come up again.
